### ISSUE TITLE
Ambiguous statement in Kelvin-Helmholtz example regarding implemented timesteppers

### ISSUE THREAD

**Issue by glwagner** [DedalusProject/dedalus#101]
The [Kelvin-Helmholtz example notebook](https://dedalus-project.readthedocs.io/en/latest/notebooks/KelvinHelmholtzInstability.html#Timestepping) states

> We have implemented *about* twenty implicit-explicit timesteppers in Dedalus.

(emphasis mine). This confusingly suggests that the precise number of timesteppers that are implemented cannot be precisely determined.

A link to the time-stepper documentation would also be friendly.

**Comment by kburns** [comment]
Thanks.  These notebooks have been pretty neglected, but I just fixed this up and a few other things in 3be0b0abf02fb006b0824826def6625cd4894f8f.
