### ISSUE TITLE
Archive releases on Zenodo and update citation instructions

### ISSUE THREAD

**Issue by namurphy** [DedalusProject/dedalus#108]
An emerging best practice is to openly archive scientific software on the [Zenodo online repository](https://zenodo.org/), or another online repository that can provide a particular version of a code with a persistent identifier such as a DOI.  If you were to create a [community on Zenodo](https://zenodo.org/communities/) for the Dedalus Project, this could also be a place where people applying Dedalus would be able to upload their scripts (which in turn would give prospective new users access to sample problems that they could expand and/or modify) and their simulation results (which would help with reproducibility).

Another possibility would be the [Journal of Open Source Software](https://joss.theoj.org/) which would be an opportunity for the code itself to undergo peer review.  Going this route would let authors cite the source code in exactly the same way as a journal article.  

After doing this, I'd also suggest updating the citation instructions to request that authors cite both the Dedalus paper and the _specific version of Dedalus_ that was used for the project they are publishing using the DOI from the Zenodo record.  The article by [Bouquin et al. 2020](https://doi.org/10.3847/1538-4365/ab7be6) goes into a lot more detail about why do do this, and there's also a  [video that goes over this article](https://www.youtube.com/watch?v=iuEtZC2Ir-A).

**Comment by jsoishi** [comment]
Hi Nick,

Thanks for this. We have been thinking about creating a hub for dedalus-related content from our userbase, and the Zenodo communties seem like a really good option for that. Do you know of any simulation code examples of that? My quick perusal turned up datasets, but no scripts or other simulation input type communities.

**Comment by namurphy** [comment]
I don't know of any simulation codes that make extensive use of the community feature on Zenodo, but here are a few peripheral examples that might give a better idea of what a Zenodo community for Dedalus could include, both as records and as metadata for the community itself.
 - [Astropy community](https://zenodo.org/communities/astropy)
 - [PlasmaPy community](https://zenodo.org/communities/plasmapy)
 - [Gkeyll community](https://zenodo.org/communities/gkeyll)

**Comment by kburns** [comment]
With the release of v3.0.0, I've setup a zenodo record for the code here: http://doi.org/10.5281/zenodo.10445656

**Comment by afraser3** [comment]
FYI Keaton: looks like there's an incomplete section on the zenodo page, see screenshot below. Doesn't look like a big deal, just thought I'd notify you in case you're worried about it.

Might be worth listing this on the "citations" page on the dedalus webpage.

<img width="742" alt="Screen Shot 2024-01-03 at 11 23 48 AM" src="https://github.com/DedalusProject/dedalus/assets/35345832/ae9f37bb-0e4a-471d-aa56-18fbcd29c493">

**Comment by kburns** [comment]
Thanks, we also have a zenodo community here: https://zenodo.org/communities/dedalus
