### ISSUE TITLE
ValueError: LHS operator interp_x is coupled along direction x.

### ISSUE THREAD

**Issue by huanglz03** [DedalusProject/dedalus#114]
*Note: Since most installation-related issues are due to specific user or machine environments rather than the Dedalus source code, we ask that you please direct installation-related questions to the [mailing list](https://groups.google.com/forum/#!forum/dedalus-users).*
What does this error means? And how to fix it? Thanks.

**Comment by kburns** [comment]
This indicates the LHS of a problem includes an interpolation operator in a periodic direction. Such an operator couples different Fourier modes, and currently cannot be computed implicitly in Dedalus.
