### ISSUE TITLE
[d3] cartesian curl not implemented

### ISSUE THREAD

**Issue by bpbrown** [DedalusProject/dedalus#118]
Cartesian coordinates appear to not have an implementation for the curl operator.  I've created a test in the `test_cartesian_operators.py` in the d3_cartesian_curl branch.  This test currently fails on a not-implemented error for both 3-d and 2-d systems.

Separately, there's a question here: in a 2-d cartesian system, should curl be `tensorsig=(c,)` or should it be a scalar?  Namely, are we 2.5-d or are we true 2-d?  Because of this uncertainty on my part, the 2-d test may be poorly formed.  The 3-d test is expected to pass.

**Comment by namurphy** [comment]
Given the uncertainty that @bpbrown mentioned in the second paragraph, it'd be good to maybe have a section in the documentation that discusses the convention that gets decided upon, or possibly a `.. note::` directive in the docstring on it.  Thank you!

**Comment by kburns** [comment]
Fixed in #131. The current approach to curls in 2D is to use skew and gradient operators.
