### ISSUE TITLE
[d3] Laplacians with NCCs in front of them fail in ball geometries

### ISSUE THREAD

**Issue by bpbrown** [DedalusProject/dedalus#123]
Problems of the form:
```
     ncc(r) * Lap(q) = F
```
and
```
      Lap(q) = F/ncc(r)
```
are failing in the ball when `ncc = f(r)`.  They work in the shell and they work in the ball if `ncc=1` (or other constants).  

The answers are slightly off, rather than just-completely-wrong.  

Here's an example when `ncc=r`:
![ncc_lap_1](https://user-images.githubusercontent.com/6025441/110049211-453f8a80-7d06-11eb-99e7-54e6868d56f0.png)

and here's `ncc=r**(1.5)`:
![ncc_lap_1 5](https://user-images.githubusercontent.com/6025441/110049314-76b85600-7d06-11eb-92aa-54a93a5e210d.png)

we do moderately well even for a system that's singular at the origin, like `ncc=r^2`:
![ncc_lap_2](https://user-images.githubusercontent.com/6025441/110049396-9ea7b980-7d06-11eb-89d9-2ceb0cdf43fa.png)

but all of these are still wrong.  

I've written a set of unit tests for both the shell and the ball in `test_lbvp.py` and have pushed them as `d3_ncc_lap`.

**Comment by kburns** [comment]
I think these are all expected to fail since since they're not analytic at the origin. `(r-1)` has incorrect parity, `sqrt(r)-1` has unbounded derivative, and `log(r)` is singular, so there's probably very slow decay of the expansion coefficients.  Maybe a better test would be to manufacture a solution that's analytic but not polynomial in` r^2`, like `cos(r^2)`.  But the inverse of it's Laplacian, as an NCC, will likely also converge slowly.

**Comment by bpbrown** [comment]
@kburns is exactly right.  The expected `cos(r^2)` test performs as expected.  I've updated the unit test to include that test and have commented out the cases that are expected to fail at `r=0`.   All tests now pass.

I've also updated the `test_marti_hydro.py` test in `examples` on the `d3_ncc_lap` branch to do a (constant) ncc diffusion test on a vector variable.  That produces the expected result (Lecoanet et al 2019, section 6.3).

**Comment by bpbrown** [comment]
Okay.  This is interesting.  It turns out the edge case is when the ncc is on a scale other than `1` and when using `dtype=np.float64`.  Unit tests updated, and we now have clear failures in `test_ball_ncc.py` too.

**Comment by bpbrown** [comment]
commit 87032c1d86a2f72039f1d44130b6cc05d5f6d78d by @kburns fixes this problem and all pytests pass or xfail as expected.

**Comment by kburns** [comment]
Fixed merged in #129.
