### ISSUE TITLE
[d3] evaluators w/ virtual file: write numbers incrementing by 2 rather than 1?

### ISSUE THREAD

**Issue by bpbrown** [DedalusProject/dedalus#128]
I'm playing around with bulk outputs in `d3-eval` using virtual files on 256 cores and they seem to be working great.  In using 894646209517b5772de2a01903d9849585c71e85 I think I've found one small interesting bug (maybe)?

I like to use the write number to label my output files when creating movie frames.  That way they're guaranteed to be in sequential order and processing a later file in the dataset won't squash earlier files (so you can hop around in a long data stream).

Right now those write numbers appear to increment by 2 rather than by one:
```
>>> print(f['scales/write_number'][:])
[ 2  4  6  8 10 12 14 16 18 20]
```
and if you do the same in the next sequential file you get:
```
[22 24 26 28 30 32 34 36 38]
```
The expected behaviour is:
```
[ 1 2 3 4 5 6 7 8 9 10]
```
etc.

My bulk output implementation is this:
```python
bulk_output = solver.evaluator.add_file_handler(data_dir+'/snapshots',sim_dt=10,max_writes=10)
bulk_output.add_task(s, name='s')
bulk_output.add_task(dot(curl(u),curl(u)), name='enstrophy')
```
I've checked, and the increment-by-2 behaviour happens if I use either more or less defined `add_tasks`, e.g.,
```python
bulk_output = solver.evaluator.add_file_handler(data_dir+'/snapshots',sim_dt=10,max_writes=10)
bulk_output.add_task(s, name='s')
```
and
```python
bulk_output = solver.evaluator.add_file_handler(data_dir+'/snapshots',sim_dt=10,max_writes=10)
bulk_output.add_task(s, name='s')
bulk_output.add_task(dot(curl(u),curl(u)), name='enstrophy')
bulk_output.add_task(dot(u,u)), name='KE')
```
produce the same write number sequences.

Is this a bug in the `write_numbers`?

**Comment by jsoishi** [comment]
Fixed in commit c239ef9.
