### ISSUE TITLE
[d3] Parallel constant conversion deadlocking

### ISSUE THREAD

**Issue by whitney-powers** [DedalusProject/dedalus#146]
Evaluate gives an array broadcast error only when run in parallel when evaluating addition.Something like `(1+field).evaluate()` produces this error. This also occurs when an expression like this appears on the RHS of the equations at least for an IVP solver.  One thread seems to be evaluated properly, but all others produce the same type of error. This error can be remedied in a fairly crude way by making 1 into a field object. 
Here is a minimal working example. When run as `mpiexec -n 2 python3 d3_eval_bug.py` it produces the error, when run as `mpiexec -n 1 python3 d3_eval_bug.py` it runs properly. The d3_eval_bug.py script reproduces the bug, and the d3_eval_working.py script demonstrates the crude workaround. These are attached as .txt files as github does not allow .py files to be uploaded
[d3_eval_bug.py.txt](https://github.com/DedalusProject/dedalus/files/6641044/d3_eval_bug.py.txt)
[d3_eval_working.py.txt](https://github.com/DedalusProject/dedalus/files/6641045/d3_eval_working.py.txt)

**Comment by whitney-powers** [comment]
Here's an example error message
`Traceback (most recent call last):`
`  File "d3_eval_bug.py", line 23, in <module>`
`    print('rank {:}, (1+f1) shape {:}'.format(rank,(1+f1).evaluate()['g'].shape`
`  File "/home/whitney/dedalus-d3/dedalus-d3/dedalus/core/future.py", line 167, in evaluate`
`    a_eval = a.evaluate(id=id, force=force)`
`  File "/home/whitney/dedalus-d3/dedalus-d3/dedalus/core/future.py", line 195, in evaluate`
`    self.operate(out)`
`  File "/home/whitney/dedalus-d3/dedalus-d3/dedalus/core/operators.py", line 1392, in operate`
`    np.copyto(out.data, arg.data)`
`  File "<__array_function__ internals>", line 5, in copyto`
`ValueError: could not broadcast input array from shape (8,0) into shape (8,4)`

**Comment by kburns** [comment]
Thanks for the report and minimal working example! This should be fixed with this commit, now on the tip of the d3 branch: cb4ac010c58a40aa614806930f56bd4ed2a32406.  Can you try it out on your other scripts when you have a chance and report back?
