### ISSUE TITLE
Error when calling fftw file

### ISSUE THREAD

**Issue by ArvinSubramaniam** [DedalusProject/dedalus#148]
Hi, I'm running one of the test examples given, and there seems to be an error with respect to the fftw package that I am unable to figure out. This error is raised for instance when solvers.step(dt) is performed. This is the relevant snippet from the error message:

~/miniconda3/lib/python3.8/site-packages/dedalus/core/basis.py in _fftw_setup(self, dtype, gshape, axis)
   1893         flags = ['FFTW_'+FFTW_RIGOR.upper()]
   1894         #print("before executing fftw")
-> 1895         plan = fftw.FourierTransform(dtype, gshape, axis, flags=flags)
   1896         temp = fftw.create_array(plan.cshape, np.complex128)
   1897         if dtype == np.float64:

~/miniconda3/lib/python3.8/site-packages/dedalus/libraries/fftw/fftw_wrappers.pyx in dedalus.libraries.fftw.fftw_wrappers.FourierTransform.__init__()

RuntimeError: FFTW could not create plans.

Any help here is welcome.

**Comment by kburns** [comment]
Hi Arvin, sorry for the long delay replying to this. Please try a fresh conda installation using the most recent conda build script, and feel free to reopen this issue with the latest library version and error messages if this error persists.
