### ISSUE TITLE
[d3] parallel-dependent issue with evaluation of laplacian

### ISSUE THREAD

**Issue by whitney-powers** [DedalusProject/dedalus#158]
Hello Dedalus team,
I have found a problem with evaluating laplacian operators in parallel runs. I believe that this is resposible for the problems I've been having with the RHS (anti)diffusion terms. I've written up a minimal working example that evaluates Lap(z**2) which should return 2 everywhere. On 1 core this has the expected behavior but on 2 or more cores this returns the wrong result. It looks like one core is evaluating correctly, but the others return nonsensical results (not all zeros like I've seen before).
Thanks for your help,
Whitney

```
import numpy as np
from mpi4py import MPI
import dedalus.public as de
​
comm = MPI.COMM_WORLD
rank = comm.rank
ncpu = comm.size
​
nx = 4
ny = 4
nz = 4
​
log2 = np.log2(ncpu)
if log2 == int(log2):
    mesh = [int(2**np.ceil(log2/2)),int(2**np.floor(log2/2))]
​
# Bases                                                                                                                                                                                                    
dtype = np.float64
​
c = de.CartesianCoordinates('x','y','z')
d = de.Distributor((c,),mesh=mesh, dtype=dtype)
​
xb = de.RealFourier(c.coords[0], size=nx, bounds=(0, 1))
yb = de.RealFourier(c.coords[1], size=ny, bounds=(0, 1))
zb = de.ChebyshevT(c.coords[2], size=nz, bounds=(0, 1))
z = zb.local_grid()
​
b = (xb, yb, zb)
​
T = d.Field(name='T', bases=b)
​
lap = de.Laplacian
​
T['g'] = z**2
print(lap(T).evaluate()['g'])

```

**Comment by whitney-powers** [comment]
It also appears that div(grad(T)) works as intended in parallel

**Comment by kburns** [comment]
Looks like the same underlying issue as #152, and the script is now working in parallel with #161.
