### ISSUE TITLE
Option to not save certain problem variables 

### ISSUE THREAD

**Issue by gokhanyalniz** [DedalusProject/dedalus#164]
Summary: Would you consider adding an option to save to disk (and reading from the disk) only the problem variables that are necessary to specify an initial condition in an initial value problem? Variables that hold wall-normal derivatives of other variables or Lagrange multipliers to satisfy constraints (pressure field for incompressibility for example) are not "necessary" in this sense. Numerically, however, such a way of restarting a problem might lead to a different trajectory than the way Dedalus does it right now, so I'm hesitant to create a pull request and would like your opinions on this.

Longer version: Dedalus saves *all* problem variables (`prob_variables`) to disk when using the `add_system(solver.state)` command as in the following code block:

```
...
prob_variables = ["u", "v", "w", "Ox", "Oz", "p"]
prob = de.IVP(domain, variables=prob_variables)
...
solver = prob.build_solver(de.timesteppers.SBDF2)
...
snapshots = solver.evaluator.add_file_handler("snapshots")
snapshots.add_system(solver.state)
```

Dedalus also expects all of `prob_variables` to be in the file loaded with `solver.load_state` as in

```
...
write, last_dt = solver.load_state("restart.h5", -1)
```

Often some problem variables are auxiliary: a variable that holds the derivative in the non-homogenous direction of another variable, or a variable whose time derivative does not appear in the system are two cases I have encountered so far. For example the code snippets here are from a 3D incompressible Navier-Stokes solver with a wall in the `y` direction. `Ox` and `Oz` (vorticity components) are derived from `u`, `v`, and `w` (velocity components) via

```
prob.add_equation("Ox - dy(w) + dz(v) = 0")
prob.add_equation("Oz - dx(v) + dy(u) = 0")
```

and `p` is the pressure field, which is not timestepped but adjusted to satisy the incompressibility condition
```
prob.add_equation("dx(u) + dy(v) + dz(w) = 0")
```

I don't want to save `Ox`, `Oz` and `p` to disk to save disk space, and potentially i/o time. The solution I came up with is to add a meta key "save", as in
```
prob.meta["Ox"]["save"] = False
prob.meta["Oz"]["save"] = False
prob.meta["p"]["save"] = False
```
(edit: this use of the meta property seems to only work for a fully Fourier domain)

and modify `add_system` in `dedalus/core/evaluator.py`, and `load_state` in `dedalus/core/solvers.py` to respect this meta key accordingly. You can see https://github.com/gokhanyalniz/dedalus/commit/876b637cd07977d3577b60451174041481f6e670 for the full implementation. One would then derive, during initiation, `Ox` and `Oz` from `u`, `v`, and `w`, and leave `p` alone to the timestepper.

However, with my (very minimal) understanding of the tau method, equations like
```
prob.add_equation("Ox - dy(w) + dz(v) = 0")
prob.add_equation("Oz - dx(v) + dy(u) = 0")
```
do not mean that `Ox["g"] == (dy(w) - dz(v)).evaluate()["g"]`, but rather the LHS differs from the RHS to machine epsilon. This would lead to a trajectory resumed in the way I propose to differ from a trajectory resumed in the way Dedalus does it right now, especially so if the system is chaotic.

I imagine a way to handle this is to derive all auxiliary fields from the primary fields, as in
```
Ox["g"] = (dy(w) - dz(v)).evaluate()["g"]
Ox["g"] = (dy(w) - dz(v)).evaluate()["g"]
```
before each "save to disk" call. But I don't know how to best hook such an operation to the existing `solver.evaluator.add_file_handler` system, and I'm not sure whether this is a good idea.

I'm loking forward to your opinions, best,
Gökhan

**Comment by kburns** [comment]
Hi Gökhan, sorry for the long delay addressing this. I think it's a good question and solution approach. But we're generally moving away from the meta keywords (they're gone completely in v3), but maybe an alternative is to just save by name the fields you want to store, instead of the full system. And then we can add an option to `load_state` to allow missing variables, e.g. not fail if it doesn't find one of the state variables in the provided file.  As you say, this may result in different trajectories than the initial simulation.  But this is already true if you're using e.g. a multistep timestepper.

**Comment by kburns** [comment]
Added in a51ffc48666d24614cd2b8502983604b83ef579b.
