### ISSUE TITLE
[d3] Integrate operator in flow_tools

### ISSUE THREAD

**Issue by mabdulla99** [DedalusProject/dedalus#177]
A small 'bug': in ```extras.flow_tools```, the integration operator is called as ```.integrate``` instead of ```.Integrate``` as committed in ```core.operators```.

**Comment by kburns** [comment]
Thanks! Yes I think it should be `.Integrate`. Would you like to open a PR?

**Comment by mabdulla99** [comment]
Just submitted one!

**Comment by kburns** [comment]
Fixed with #181.
