### ISSUE TITLE
[d3] Merging virtual files into single files

### ISSUE THREAD

**Issue by evanhanders** [DedalusProject/dedalus#182]
Virtual files (and the partial files they read) are starting to cause me issues with my filesystem quotas on Pleiades. I've created a little script based on d2's merging logic that merges a virtual file into a single, merged dataset (attached here, in .txt format: [merge_virtual_files.py.txt](https://github.com/DedalusProject/dedalus/files/8227629/merge_virtual_files.py.txt)).

If there's interest, I can improve this and work towards a pull request to put this into d3's tools/post.py file.

**Comment by kburns** [comment]
Yeah it would definitely be nice to have some flavor of this, it's just a shame that it (and the current FileHandler in geneeral) requires so much boilerplate -- as far as I've seen, there's no simpler copy mechanism that can merge together virtual datasets.  I hate merging in general so it would be really nice to get parallel HDF5 or another parallel-write system like zarr working, maybe as separate FileHandler subclasses.

**Comment by kburns** [comment]
Yeah it would be great to have a PR for adding this, thanks!

**Comment by evanhanders** [comment]
Sounds good! I'll work on getting a preliminary PR together this week or so.
