### ISSUE TITLE
Example of `Compound` basis?

### ISSUE THREAD

**Issue by hdrake** [DedalusProject/dedalus#210]
I was re-reading the [Burns et al. (2020) Dedalus paper](https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.2.023068) and noticed the section of Compound basis functions (e.g. Compound Chebyshev). I am working on a problem with an interior boundary layer that would benefit from this, but it's not clear from the Docs or the examples how to do it.

Does anyone have an example of a problem with a Compound Basis or advice for how to implement it?

**Comment by afraser3** [comment]
Hi Henri,

If you're talking about d2, then here's an example I had lying around in an old script, where `splitdomain` was a flag that would either use a compound basis or a single Chebyshev basis:

    # Build domain
    if splitdomain==False:
        z_basis = de.Chebyshev('z', Nz, interval=(-0.5*Lz,0.5*Lz), dealias=3/2)
    else:
        z_basis1 = de.Chebyshev('z1', int(Nz/2), interval=(-0.5*Lz,0), dealias=3/2)
        z_basis2 = de.Chebyshev('z2', int(Nz/2), interval=(0,0.5*Lz), dealias=3/2)
        z_basis = de.Compound('z', (z_basis1, z_basis2), dealias=3/2)
    x_basis = de.Fourier('x', Nx, interval=(-0.5*Lx,0.5*Lx), dealias=3/2)
    domain = de.Domain([x_basis,z_basis], grid_dtype=np.float64)
