### ISSUE TITLE
[d3]Is EVP support 2D eigenproblem like BiGlobal stability analysis?

### ISSUE THREAD

**Issue by demonh6** [DedalusProject/dedalus#217]
I'm trying to solve the eigenvalue problem of schrodinger equation of two-dimensional stationary harmonic oscillator by Dedalus. But I ran into difficulties and didn't find similar examples to refer to. I wonder if v2_master and v3_master can solve BiGlobal Problem.
Thanks for answering me!!!
Here are the errors I encountered
In v2_master: NameError: name 'dy' is not defined. Did you mean: 'dx'? (How to make EVP dealing with dx and dy at the same time)
In v3_master:  solver.solve_sparse(solver.subproblems[0], 10, 2) ------NotImplementedError 
Another multi equations problem (such as NS equations)
In v3_master:   INFO :: Building subproblem matrices 1/1 (~100%) Elapsed: 1s, Remaining: 0s, Rate: 9.8e-01/s
Traceback (most recent call last): ------RuntimeError: Factor is exactly singular

**Comment by kburns** [comment]
Hi, please use the mailing list for questions regarding how to formulate a problem in Dedalus.
