### ISSUE TITLE
Pip install fails

### ISSUE THREAD

**Issue by tomass2077** [DedalusProject/dedalus#228]
pip3 install dedalus output:

`Defaulting to user installation because normal site-packages is not writeable
Collecting dedalus
  Using cached dedalus-2.2207.1.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: h5py>=2.10.0 in /home/tomass/.local/lib/python3.10/site-packages (from dedalus) (3.7.0)
Requirement already satisfied: scipy>=1.4.0 in /home/tomass/.local/lib/python3.10/site-packages (from dedalus) (1.9.2)
Collecting pytest
  Using cached pytest-7.1.3-py3-none-any.whl (298 kB)
Requirement already satisfied: numpy>=1.20.0 in /home/tomass/.local/lib/python3.10/site-packages (from dedalus) (1.23.3)
Collecting pytest-cov
  Using cached pytest_cov-4.0.0-py3-none-any.whl (21 kB)
Collecting docopt
  Using cached docopt-0.6.2-py2.py3-none-any.whl
Collecting pytest-benchmark
  Using cached pytest_benchmark-3.4.1-py2.py3-none-any.whl (50 kB)
Requirement already satisfied: mpi4py>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from dedalus) (3.1.3)
Collecting pytest-parallel
  Using cached pytest_parallel-0.1.1-py3-none-any.whl (7.0 kB)
Requirement already satisfied: matplotlib in /home/tomass/.local/lib/python3.10/site-packages (from dedalus) (3.6.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/tomass/.local/lib/python3.10/site-packages (from matplotlib->dedalus) (2.8.2)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3/dist-packages (from matplotlib->dedalus) (21.3)
Requirement already satisfied: cycler>=0.10 in /home/tomass/.local/lib/python3.10/site-packages (from matplotlib->dedalus) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/tomass/.local/lib/python3.10/site-packages (from matplotlib->dedalus) (1.4.4)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib->dedalus) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib->dedalus) (9.0.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/tomass/.local/lib/python3.10/site-packages (from matplotlib->dedalus) (4.37.4)
Requirement already satisfied: contourpy>=1.0.1 in /home/tomass/.local/lib/python3.10/site-packages (from matplotlib->dedalus) (1.0.5)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Requirement already satisfied: attrs>=19.2.0 in /home/tomass/.local/lib/python3.10/site-packages (from pytest->dedalus) (22.1.0)
Collecting py>=1.8.2
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Requirement already satisfied: tomli>=1.0.0 in /home/tomass/.local/lib/python3.10/site-packages (from pytest->dedalus) (2.0.1)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting py-cpuinfo
  Using cached py_cpuinfo-8.0.0-py3-none-any.whl
Collecting coverage[toml]>=5.2.1
  Using cached coverage-6.5.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (213 kB)
Collecting tblib
  Using cached tblib-1.7.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib->dedalus) (1.16.0)
Building wheels for collected packages: dedalus
  Building wheel for dedalus (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/tomass/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpqcq1b0nl
       cwd: /tmp/pip-install-weap5xss/dedalus_3a40a1332ca6438ab6e7b55a01153cc2
  Complete output (90 lines):
  Looking for mpi include path
    Cannot find env var MPI_INCLUDE_PATH
  Looking for mpi prefix
    Found matching library in /usr/lib
  Looking for fftw include path
    Cannot find env var FFTW_INCLUDE_PATH
  Looking for fftw prefix
    Found matching library in /usr/lib
  Looking for fftw library path
    Cannot find env var FFTW_LIBRARY_PATH
  Looking for fftw prefix
    Found matching library in /usr/lib
  Looking for mpi library path
    Cannot find env var MPI_LIBRARY_PATH
  Looking for mpi prefix
    Found matching library in /usr/lib
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.10
  creating build/lib.linux-x86_64-3.10/dedalus
  copying dedalus/public.py -> build/lib.linux-x86_64-3.10/dedalus
  copying dedalus/__main__.py -> build/lib.linux-x86_64-3.10/dedalus
  copying dedalus/dev.py -> build/lib.linux-x86_64-3.10/dedalus
  copying dedalus/__init__.py -> build/lib.linux-x86_64-3.10/dedalus
  creating build/lib.linux-x86_64-3.10/dedalus/extras
  copying dedalus/extras/flow_tools.py -> build/lib.linux-x86_64-3.10/dedalus/extras
  copying dedalus/extras/atmospheres.py -> build/lib.linux-x86_64-3.10/dedalus/extras
  copying dedalus/extras/plot_tools.py -> build/lib.linux-x86_64-3.10/dedalus/extras
  copying dedalus/extras/__init__.py -> build/lib.linux-x86_64-3.10/dedalus/extras
  creating build/lib.linux-x86_64-3.10/dedalus/libraries
  copying dedalus/libraries/matsolvers.py -> build/lib.linux-x86_64-3.10/dedalus/libraries
  copying dedalus/libraries/__init__.py -> build/lib.linux-x86_64-3.10/dedalus/libraries
  creating build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/basis.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/problems.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/solvers.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/pencil.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/distributor.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/field.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/domain.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/metadata.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/operators.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/evaluator.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/future.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/__init__.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/timesteppers.py -> build/lib.linux-x86_64-3.10/dedalus/core
  copying dedalus/core/system.py -> build/lib.linux-x86_64-3.10/dedalus/core
  creating build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/dispatch.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/plot_op.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/progress.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/array.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/parsing.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/sparse.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/cache.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/config.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/logging.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/post.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/parallel.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/__init__.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/general.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  copying dedalus/tools/exceptions.py -> build/lib.linux-x86_64-3.10/dedalus/tools
  creating build/lib.linux-x86_64-3.10/dedalus/tests
  copying dedalus/tests/test_bvp.py -> build/lib.linux-x86_64-3.10/dedalus/tests
  copying dedalus/tests/test_nlbvp.py -> build/lib.linux-x86_64-3.10/dedalus/tests
  copying dedalus/tests/test_output.py -> build/lib.linux-x86_64-3.10/dedalus/tests
  copying dedalus/tests/test_evp.py -> build/lib.linux-x86_64-3.10/dedalus/tests
  copying dedalus/tests/__init__.py -> build/lib.linux-x86_64-3.10/dedalus/tests
  copying dedalus/tests/test_ivp.py -> build/lib.linux-x86_64-3.10/dedalus/tests
  copying dedalus/tests/test_matsolvers.py -> build/lib.linux-x86_64-3.10/dedalus/tests
  creating build/lib.linux-x86_64-3.10/dedalus/libraries/fftw
  copying dedalus/libraries/fftw/__init__.py -> build/lib.linux-x86_64-3.10/dedalus/libraries/fftw
  creating build/lib.linux-x86_64-3.10/dedalus/tests/special_functions
  copying dedalus/tests/special_functions/bessel.py -> build/lib.linux-x86_64-3.10/dedalus/tests/special_functions
  copying dedalus/tests/special_functions/airy.py -> build/lib.linux-x86_64-3.10/dedalus/tests/special_functions
  copying dedalus/tests/special_functions/__init__.py -> build/lib.linux-x86_64-3.10/dedalus/tests/special_functions
  copying dedalus/dedalus.cfg -> build/lib.linux-x86_64-3.10/dedalus
  copying dedalus/examples.tar.gz -> build/lib.linux-x86_64-3.10/dedalus
  running build_ext
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/dedalus
  creating build/temp.linux-x86_64-3.10/dedalus/libraries
  creating build/temp.linux-x86_64-3.10/dedalus/libraries/fftw
  x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Idedalus/libraries/fftw/ -I/tmp/pip-build-env-bvx5qepg/overlay/local/lib/python3.10/dist-packages/numpy/core/include -I/tmp/pip-build-env-bvx5qepg/overlay/local/lib/python3.10/dist-packages/mpi4py/include -I/usr/include -I/usr/include -I/usr/include/python3.10 -c dedalus/libraries/fftw/fftw_wrappers.c -o build/temp.linux-x86_64-3.10/dedalus/libraries/fftw/fftw_wrappers.o -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Wno-unused-function
  dedalus/libraries/fftw/fftw_wrappers.c:1514:3: error: unknown type name ‘MPI_Message’
   1514 |   MPI_Message ob_mpi;
        |   ^~~~~~~~~~~
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for dedalus
Failed to build dedalus
ERROR: Could not build wheels for dedalus, which is required to install pyproject.toml-based projects`

**Comment by kburns** [comment]
The nightly build which follows the conda installation instructions is still succeeding, so it looks like there is probably an issue with the python environment you're trying to install to.  I'd recommend trying the conda installation, and if issues remain please get in touch on the mailing list with the full info of how you've built the python environment, etc.
