### ISSUE TITLE
Vestigial class factories in operators.py don't work in d3 but are still attached to fields.

### ISSUE THREAD

**Issue by jsoishi** [DedalusProject/dedalus#244]
The class factory functions, for example `differentiate()` in `operators.py` rely on `domain.get_space_object()`, which no longer exists. These functions are still attached to fields, but do not work. It is confusing for users to have these methods that do not work. We should either update the class factory functions or delete them entirely.

**Comment by kburns** [comment]
Removed in 0b0d131. Keeping the old factories around incase we decide the revive them -- we currently use one for interpolation, and possibly might want others later.
