### ISSUE TITLE
Construct LHS system matrix

### ISSUE THREAD

**Issue by kharazity** [DedalusProject/dedalus#245]
Hey everyone,

I wanted to do some numerical testing on the SEM. In particular, I want to study the condition numbers and bandwidth of the produced SE matrices. I wanted to start with a simple example like that in `/examples/ldvp_2d_poisson/poisson.py`. 

First, how do I extract the final LHS system matrix that is used in the linear solve? Does this linear system include the boundary conditions and the Dirichlet recombination steps? What is the best way to efficiently extract this system and estimate it's conditioning?

**Comment by jsoishi** [comment]
Hi,

The issue tracker is not the best place for questions like these. Please ask this at our mailing list, https://groups.google.com/g/dedalus-users and we would be happy to help!

Jeff
