### ISSUE TITLE
Solving Poisson equation in the ocean

### ISSUE THREAD

**Issue by miniufo** [DedalusProject/dedalus#250]
Thanks for this excellent symbolic solver for PDEs.  Just a quick question.  If I want to solve a Poisson equation on a domain like the ocean, with a DEM file describing the irregular ocean grids, is it possible to use this package with spectral method?  Maybe it is convenient to do this as a demo?

**Comment by kburns** [comment]
This package is aimed at global spectral methods, so generally wouldn't be well suited to that sort of thing. I'd suggest looking into FEM or SEM packages instead.
