### ISSUE TITLE
Installation currently requires Cython<3

### ISSUE THREAD

**Issue by geoffstanley** [DedalusProject/dedalus#266]
Trying to install Dedalus3 following the [recommended instructions](https://dedalus-project.readthedocs.io/en/latest/pages/installation.html#full-stack-conda-installation-recommended) worked for me in the past, but just failed with a `Getting requirements to build wheel did not run successfully.` error, including a lot of  `Error compiling Cython file` lines.

Following [this](https://discuss.python.org/t/getting-requirements-to-build-wheel-did-not-run-successfully-exit-code-1/30365), I got Dedalus3 re-installed by adding a `Cython<3` requirement to the `pip3 install` command from the recommended instructions:

```
echo "Cython<3" > cython_constraint.txt
CC=mpicc PIP_CONSTRAINT=cython_constraint.txt pip3 install --no-cache http://github.com/dedalusproject/dedalus/zipball/master/
```

Just noting this in case anyone else has trouble, or perhaps the recommended instructions should be updated to reflect this. I guess it's just temporary though until Dedalus3 gets working with Cython 3.

**Comment by kburns** [comment]
Thanks, yeah we have a similar fix to pin cython via conda in the testing pipeline, and it looks like it's enough for now.

**Comment by geoffstanley** [comment]
I see you've updated the installation instructions and build requirements. Perfect, thanks!
