### ISSUE TITLE
Error in running tutorials of dedalus

### ISSUE THREAD

**Issue by cshsgy** [DedalusProject/dedalus#273]
Hi,
I encountered a problem in running the tutorials of dedalus.
Traceback (most recent call last):
  File "/Users/sihechen/QG_Dedalus/tutorial/example.py", line 15, in <module>
    coords = d3.CartesianCoordinates('x', 'y')
             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'dedalus.public' has no attribute 'CartesianCoordinates'
I can run codes without the coords attribute, but I still want to start with the tutorials first.
Any ideas?
Thanks so much in advance!

**Comment by kburns** [comment]
It looks like you have installed v2 of the code but are trying to run the v3 tutorials. Please check the installation instructions for v3.
