### ISSUE TITLE
np.real operator in equations does not take real part

### ISSUE THREAD

**Issue by lecoanet** [DedalusProject/dedalus#298]
It seems like if you add an equation with an operator "np.real" the code runs without complaining, but it does not appear to take the real part. I will try to come up with a simple example to demonstrate this.

**Comment by kburns** [comment]
np.real and np.imag are not ufuncs, so I think its treating dedalus fields as just random objects. It looks like we might be able to circumvent this behavior by defining .real and .imag properties that return the operators we want.

**Comment by kburns** [comment]
Added real and imag properties for operands in #305.

**Comment by kburns** [comment]
Closing at #305 has been merged.
