### ISSUE TITLE
Add xarray field conversion / output handler

### ISSUE THREAD

**Issue by kburns** [DedalusProject/dedalus#56]
**Original report ([archived issue](https://DedalusProject.github.io/dedalus_bitbucket_history/#!/dedalus-project/dedalus/issues/56)) by Keaton Burns (Bitbucket: [kburns](https://bitbucket.org/%7B3d3e64f1-bf12-45df-b655-4543d8fb34c4%7D/)).**

----------------------------------------
We should consider simple xarray conversion operators for fields, as well as xarray handlers that produce xarray objects and/or write to disk using xarray.

**Comment by kburns** [comment]
Looks like we may be able to implement an xarray backend that lazily reads Dedalus HDF5 files: https://xarray.pydata.org/en/stable/internals/how-to-add-new-backend.html#rst-lazy-loading

It might also be worth revisiting the idea of making our outputs netCDF compatible, but I'm really not sure what that would require: https://www.unidata.ucar.edu/software/netcdf/

**Comment by kburns** [comment]
Looks like netcdf does not support complex numbers, so that's out.

**Comment by afraser3** [comment]
It's ugly, but I've seen people do complex numbers with netCDF by basically introducing an additional axis of length 2 that corresponds to the real/imaginary parts.

I guess that means you would have to change things pretty dramatically for all the Dedalus users who don't use netCDF. Doesn't sound great.

**Comment by kburns** [comment]
A basic xarray interface has been added with #213.  I'll close this for now, but would definitely be open to further discussions about enhancing this interface with lazy loading, etc., if anyone needs that and is interested in contributing.
