### ISSUE TITLE
Memory leak from evaluating operations on Q_time branch

### ISSUE THREAD

**Issue by evanhanders** [DedalusProject/dedalus#83]
Hi Dedalus dev team,

I'm currently running some d3, marti-benchmark-esque simulations in the full ball on the tip of the Q_time branch (commit  205c9eb). I've been using Dedalus operators (e.g., arithmetic.DotProduct) to define some of my output tasks, and I found that when I started using the Q_time branch (compared to d3 from 2 weeks ago before the speed improvements), these dot operations started to cause memory leaks.

Here's a marginally stripped down example of this compared to my full code:
[bad_memory_rotating_rbc_ball.py.txt](https://github.com/DedalusProject/dedalus/files/4899611/bad_memory_rotating_rbc_ball.py.txt) (Github made me upload it as a .txt instead of .py, so just strip off the .txt when you download it to try running it). I run this on 64 cores on pleiades like:

`mpiexec_mpt -n 64 python3 bad_memory_rotating_rbc_ball.py --mesh=8,8`

I've put a dot() operation in on line 301 in the main IVP loop. With that operation, the memory slowly grows. Without that operation, the memory is constant over the course of the simulation evolution.

I think this is a bug, but it's also possible that I'm using the operation wrong. Help! Thanks,
Evan

**Comment by kburns** [comment]
Can you check if it's the instantiation of the operator or the evaluation that's causing the leak?

**Comment by evanhanders** [comment]
I can! Good point. It seems to be the instantiation, which means that I'll just instantiate before the loop (as I should've been doing anyways) and just do evaluations during the loop.

To clarify, doing this:

```
dotter = dot(u, u)
while solver.ok:
    dotter.evaluate()
```

Does not result in a memory leak. Doing this (without even evaluating):

```
while solver.ok:
    dotter = dot(u, u)
```

Does result in constantly growing memory with time (which makes sense).
