### ISSUE TITLE
[d3] Field imports Power() from wrong place

### ISSUE THREAD

**Issue by bpbrown** [DedalusProject/dedalus#85]
In `d3`, it appears that the `Power()` operator is being incorrectly imported from `.arithmetic` rather than `.operators` (where `Power()` is currently implemented).  The full error looks like this:

```
Traceback (most recent call last):
  File "j2011_hydro.py", line 191, in <module>
    Phi = trace(dot(e, e)) - 1/3*(trace_e**2)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/field.py", line 107, in __pow__
    from .arithmetic import Power
ImportError: cannot import name 'Power' from 'dedalus.core.arithmetic' (/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/arithmetic.py)
```

The solution seems to be to import from `.operators`, but I wasn't sure whether we intend `Power()` to live in `.operators` or `.arithmetic`.

**Comment by kburns** [comment]
Still an issue?

**Comment by kburns** [comment]
Closing as this seems to have been fixed at some point and powers are now working in d3.
