### ISSUE TITLE
h5py deprecation warning

### ISSUE THREAD

**Issue by navidcy** [DedalusProject/dedalus#87]
I get this warning a lot.
Thought I'd put it here; not sure if this was fixed on the latest version.

```python
~/.local/lib/python3.7/site-packages/dedalus/tools/post.py:349: H5pyDeprecationWarning: other_ds.dims.create_scale(ds, name) is deprecated. Use ds.make_scale(name) instead.
```

**Comment by kburns** [comment]
Thanks Navid,but this has already been fixed on master (https://github.com/DedalusProject/dedalus/issues/69).
