### ISSUE TITLE
Version identifier

### ISSUE THREAD

**Issue by navidcy** [DedalusProject/dedalus#91]
Is there a way to print out what version of dedalus I'm using. E.g., implementing something like this could be useful:

```python
import dedalus
dedalus.__version__
```

Or is there something similar already implemented?

**Comment by kburns** [comment]
The version is currently specified in `setup.py`.  You can see it from the command line with `pip show dedalus` or from python with `import pkg_resources; pkg_resources.get_distribution('dedalus').version`.

**Comment by kburns** [comment]
Made this a bit easier with https://github.com/DedalusProject/dedalus/commit/4e7ae5e2e8167c6be4c3414b0416a40eb7728a86, so you can now get the version with `dedalus.__version__`.
